### ISSUE TITLE
{'success': False, 'code': 602, 'message': 'Signature verification failed!'} #1

### ISSUE THREAD

**Issue by megalodn** [makarworld/pymexc#14]
The futures API works fine for some private methods, e.g. 'open_positions'.
However, when using other methods, e.g. 'assets' or 'cancel_order' I get the error described in the header. 

I gave my API key all available rights.

**Comment by makarworld** [comment]
check this -> https://github.com/makarworld/pymexc/issues/1

> The MEXC Futures API is currently not operational.
> Information on API availability can be found here -> https://t.me/MEXCAPIsupport
