### ISSUE TITLE
Signature verification failed on futures api

### ISSUE THREAD

**Issue by Mackming** [makarworld/pymexc#6]
On all the Get requests, signature verification succeeds, but when any post request is sent, signature verification fails. Any solution?

**Comment by makarworld** [comment]
Provide some of your code for make requests.

**Comment by imbashamba** [comment]
same issue, here's my code

```
from pymexc import futures

api_key = ""
api_secret = ""

# initialize HTTP client
futures_client = futures.HTTP(api_key = api_key, api_secret = api_secret)

# make http request to api
print(futures_client.index_price("SOL_USDT"))
order = futures_client.trigger_order("SOL_USDT", 1, 3, 1, 92, 2, 1, 5, 1)
print(order)
```
output:
{'success': True, 'code': 0, 'data': {'symbol': 'SOL_USDT', 'indexPrice': 95.639, 'timestamp': 1707240599818}}
{'success': False, 'code': 602, 'message': 'Signature verification failed!'}

**Comment by makarworld** [comment]
Problem on MEXC futures api side. 
As moderators said [(msg)](https://t.me/MEXCAPIsupport/96243): **"Futures not support api trading but still support query info"**. 

You can ask about api in official MEXC api support chat -> **[t.me/MEXCAPIsupport](https://t.me/MEXCAPIsupport)**

**Comment by AliM1988** [comment]
Some one show is a trick to use Trade in futures:
https://www.youtube.com/watch?v=FBlf0d0Kn_Q

**Comment by sirouk** [comment]
Yup, I have the code. I picked it up from the dev.

**Comment by makarworld** [comment]
> Yup, I have the code. I picked it up from the dev.

Do you really buy it from dev? Can you write me -> https://t.me/abuztrade

**Comment by makarworld** [comment]
> Someone shows there is a trick to use Trade in futures: https://www.youtube.com/watch?v=FBlf0d0Kn_Q

Write me if you really buy it plz https://t.me/abuztrade
